### ISSUE TITLE
Github Page not accessible at https://nodeschool.io/landshut

### ISSUE THREAD

**Issue by DanielHilpoltsteiner** [nodeschool/landshut#1]
What i have done: 
Created a static site: 
 - first try with jekyll (followed process from augsburg chapter) => not working
 - second try with gatsby (followed vancouver chapter) => not working
 - trying same gatsby on a repository under my own github account => working

Is there something in the settings (can not access), which needs to be enabled?  
Because i now think the problem is not the code. 

Result from the Gatsby build and deployment:
> gh-pages -d public
Published

Also the artefacts are accessible at the gh-pages branch. 

Has anyone an idea on this? Would appreciate it!

**Comment by WanielDeiss** [comment]
fixed 🎉
